### ISSUE TITLE
nsis 3.x

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabbuild#3]
Noticed that we are using NSIS v2.46.5-Unicode, there was a pre-alpha of 2.50 but they gave up on that as they switched to doing NSIS 3..  looking at that we see that they added unicode support in it:

http://nsis.sourceforge.net/News
> Long-awaited version 3 of NSIS is finally ready. It comes with optional Unicode support, still works on all the same versions of Windows, supports Windows 10, and adds a lot of other small features and fixes

so might be time to try that out to see if it works better for our purposes..

**Comment by thezoggy** [comment]
" NSIS 3 is basically NSIS 2.46 merged with the Unicode fork + additional bugfixes. Most of the changes are in the compiler and not in the generated installers. " is what I see people saying..

**Comment by Safihre** [comment]
I can try... It was such an incredible pain to get everything to work in the first place. The detection for running Service, auto-adding of firewall rules.

**Comment by Safihre** [comment]
Well.. That's weird:
https://ci.appveyor.com/project/Safihre/sabbuild/build/1.0.36

**Comment by Safihre** [comment]
Oke it works now:
https://github.com/sabnzbd/sabbuild/releases/tag/2.1.0-beta1-nsis-5

Doesn't look any different, nor is the filesize any smaller.
I already see that it doesn't detect anymore if SABnzbd.exe is already running..

_If it ain't broken, don't fix it?_

**Comment by thezoggy** [comment]
main reason i suggested the upgrade was for the windows 10 related support..  as people have cloud/local accounts and permission oddities that can happen

**Comment by Safihre** [comment]
We had so far [~90.000 downloads ](http://www.safihre.com/sabnzbd/stats.html) of the `setup.exe` for 2.0.0 and no problems, I remember only 1 user on the forum after the last big Win10 update before the Creators update.
But that was months ago during Beta/RC stage, so I think we are safe with the current NSIS?

**Comment by thezoggy** [comment]
probably so, but were also good with python2 :)

**Comment by Safihre** [comment]
Heheh, true! I was just watching all those PyCon videos.. 
But seems to get more speed out of SAB, we will need to either convert to Python3 or write larger sections in C-modules so we can do more things outside the GIL.

**Comment by thezoggy** [comment]
well python3 isnt magical in the sense were still going to be interrupted lang.. but because python3 came out after python2 there is a lot of stuff that it does natively without relying on libs.. but older 'native' python3 code is not always better than newer python2 lib code. thus, you actually have less control over what bugs because you leave it up to the user's python version to dictate what code is being run instead of just forcing a library requirement that can be updated independently of the system python. 

the huge benefit I see that sab can get with python3 is the better unicode handling.. instead of having to do conversions/hacks..

**Comment by thezoggy** [comment]
oh and about GIL with python 3.. 
https://www.reddit.com/r/Python/comments/4vyg2m/threadinglocking_is_4x_as_fast_on_python_3_vs/

can see that the backported GIL changes to python 2.7 are better than python 3.x
so it depends on what your doing with it.. python3 may actually be slower as its somewhat more bloated than python2...
