### ISSUE TITLE
nsis 3

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabbuild#5]
I notice that we still run with really old nsis 2.x
https://github.com/sabnzbd/sabbuild/blob/eca2b5a3c60e6f592d7f2fd104b6d9f95e41a7ec/appveyor.yml#L8

I don't see a reason we should be using it anymore as NSIS 3 = NSIS 2.5x + Unicode, with v3.05 from dec 2019 it does support py3 now as well.
https://nsis.sourceforge.io/Main_Page

I noticed you were trying to include nsis as part of the repo, I assume to pull down faster?

I see appveyor is one version behind, 3.04 -- https://www.appveyor.com/docs/windows-images-software/
I'll ping them to update

**Comment by Safihre** [comment]
Will switch to NSIS 3 for 3.1.x. Already created a test-branch and it seems to work just fine with AppVeyor's NSIS.
Totally missed that AppVeyor already provides it! Thanks for letting me know, I was spending way too much time fetching the recent version from sourceforge while it's not needed at all.

**Comment by thezoggy** [comment]
just bumped my appveyor ghi about updating nsis to latest since they are now a few versions behind
https://github.com/appveyor/ci/issues/3450

**Comment by Safihre** [comment]
Great!

**Comment by thezoggy** [comment]
looks like they added nsis 3.06.1 but only to vs2019:
https://github.com/appveyor/ci/milestone/184?closed=1

**Comment by Safihre** [comment]
👍
